name: new_one

concurrency: 1

on:
  workflow_dispatch

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID}}

jobs:
  deploy:
    environment: dev
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks Bundle
        working-directory: dab_demo
        run: databricks bundle validate 
        env:
          DATABRICKS_BUNDLE_ENV: dev

      - name: Deploy Databricks Bundle
        working-directory: dab_demo
        run: databricks bundle deploy --auto-approve
        env:
          DATABRICKS_BUNDLE_ENV: dev
