name: deploy_to_dev_dab

concurrency: deploy_to_dev_dab # ensures only one deploy runs at a time

on:
  workflow_dispatch:

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  deploy:
    environment: dev
    name: "Deploy Bundle to Dev"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks Bundle
        working-directory: dab_demo
        run: databricks bundle validate 
        env:
          DATABRICKS_BUNDLE_ENV: dev

      - name: Deploy Databricks Bundle
        working-directory: dab_demo
        run: databricks bundle deploy 
        env:
          DATABRICKS_BUNDLE_ENV: dev
